# Generated by Django 6.0.5 on 2026-06-02 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=2, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=15, verbose_name='Tingkat Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN Transaksi'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='A-Poin'),
        ),
        migrations.AddField(
            model_name='user',
            name='stamps',
            field=models.IntegerField(default=0, verbose_name='Stamp Digital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Default'),
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label Alamat (misal: Rumah, Kantor)')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Nama Penerima')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon Penerima')),
                ('full_address', models.TextField(verbose_name='Alamat Lengkap')),
                ('is_default', models.BooleanField(default=False, verbose_name='Alamat Utama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Warga')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
