# Generated by Django 6.0.5 on 2026-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_gender_user_member_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WargaVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('token', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Token Unik')),
                ('is_used', models.BooleanField(default=False, verbose_name='Sudah Digunakan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warga', 'Warga'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
