# Generated by Django 6.0.5 on 2026-06-02 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='ID Pesanan')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Pembayaran')),
                ('shipping_method', models.CharField(choices=[('pickup', 'Ambil Sendiri'), ('delivery', 'Kirim ke Rumah')], default='pickup', max_length=20, verbose_name='Metode Pengiriman')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Alamat Pengiriman')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending / Belum Bayar'), ('paid', 'Lunas / Terbayar'), ('failed', 'Gagal'), ('expired', 'Kedaluwarsa')], default='pending', max_length=20, verbose_name='Status Pembayaran')),
                ('shipping_status', models.CharField(choices=[('proses', 'Diproses'), ('siap_diambil', 'Siap Diambil'), ('sedang_diantar', 'Sedang Diantar'), ('selesai', 'Selesai')], default='proses', max_length=20, verbose_name='Status Pengiriman')),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Snap Token Midtrans')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diperbarui')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Warga')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID Produk')),
                ('product_name', models.CharField(max_length=150, verbose_name='Nama Produk')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
