# Generated by Django 6.0.5 on 2026-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('midtrans', 'Midtrans (Online)'), ('cod', 'Bayar di Tempat (COD)')], default='midtrans', max_length=20, verbose_name='Metode Pembayaran'),
        ),
    ]
