# Generated by Django 6.0.5 on 2026-06-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori / Tipe Barang')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga')),
                ('image', models.CharField(default='📦', max_length=50, verbose_name='Emoji / Gambar')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
