# Generated by Django 6.0.5 on 2026-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='📦', max_length=500, verbose_name='Emoji / Gambar'),
        ),
    ]
