# Generated by Django 6.0.5 on 2026-06-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(verbose_name='Poin Didapat')),
                ('stamps_earned', models.IntegerField(verbose_name='Stamp Didapat')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Belanja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Didistribusikan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_logs', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
